### ISSUE TITLE
Modify file pattern matching to exclude irrelevant files

### ISSUE THREAD

**Issue by loisaidasam** [yarnjs/yarn#31]
https://github.com/yarnjs/yarn/blob/c5a8efe29a5cb2a792cbefa7b0ea12441733b2fe/lib/index.js#L169

Would prefer my `package.json` not be copied over to my static site. Or my `_config.yml.original` (dunno how many folks will have that one tho)

**Comment by hswolff** [comment]
should be fixed via the (just published) `0.9.0`!
